config/routes.rb
Ceshi::Application.routes.draw do

  resources :infos

  devise_for :users

  mount Refinery::Core::Engine, :at => '/'

end

app/models/info.rb
class Info < ActiveRecord::Base
  attr_accessible :title
end

app/models/region.rb
class Region < ActiveRecord::Base
  has_ancestry

  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @infos }
    end
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
    @info = Info.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/new
  # GET /infos/new.json
  def new
    @info = Info.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @info }
    end
  end

  # GET /infos/1/edit
  def edit
    @info = Info.find(params[:id])
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(params[:info])

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render json: @info, status: :created, location: @info }
      else
        format.html { render action: "new" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /infos/1
  # PUT /infos/1.json
  def update
    @info = Info.find(params[:id])

    respond_to do |format|
      if @info.update_attributes(params[:info])
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info = Info.find(params[:id])
    @info.destroy

    respond_to do |format|
      format.html { redirect_to infos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_form.html.erb
<%= form_for(@info) do |f| %>
  <% if @info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @info.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/infos/edit.html.erb
<h1>Editing info</h1>

<%= render 'form' %>

<%= link_to 'Show', @info %> |
<%= link_to 'Back', infos_path %>

app/views/infos/index.html.erb
<h1>Listing infos</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @infos.each do |info| %>
  <tr>
    <td><%= info.title %></td>
    <td><%= link_to 'Show', info %></td>
    <td><%= link_to 'Edit', edit_info_path(info) %></td>
    <td><%= link_to 'Destroy', info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Info', new_info_path %>

app/views/infos/new.html.erb
<h1>New info</h1>

<%= render 'form' %>

<%= link_to 'Back', infos_path %>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @info.title %>
</p>


<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>

app/views/refinery/_content_page.html.erb
<%= render_content_page(@page, {
      :hide_sections => local_assigns[:hide_sections],
      :can_use_fallback => !local_assigns[:show_empty_sections] && !local_assigns[:remove_automatic_sections]
    }) %>
<%= render '/refinery/draft_page_message' unless @page.nil? or @page.live? -%>

app/views/refinery/_draft_page_message.html.erb
<aside class='page_not_live'>
  <%= t('.not_live') %>
</aside>

app/views/refinery/_footer.html.erb
<p>
  <%= t('.copyright', :year => Time.now.year,
                      :site_name => Refinery::Core.site_name) %>
</p>

app/views/refinery/_google_analytics.html.erb
<% page_code = Refinery::Core.google_analytics_page_code.to_s.strip %>
<% unless local_request? or refinery_user? or page_code =~ /^(UA-xxxxxx-x)?$/ -%>
<!-- asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet -->
<script>var _gaq=[['_setAccount','<%= page_code %>'],['_trackPageview'],['_trackPageLoadTime']];(function(d,t){
var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
g.async=1;g.src='//www.google-analytics.com/ga.js';s.parentNode.insertBefore(g,s)
}(document,'script'))</script>
<% end -%>

app/views/refinery/_head.html.erb
<head>
  <meta charset='<%= Rails.application.config.encoding %>' />
  <!--[if IE]><meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" /><![endif]-->
  <title><%= browser_title(yield(:title)) %></title>
  <%= raw %(<meta name="description" content="#{@meta.meta_description}" />) if @meta.meta_description.present? -%>
  <%= raw %(<meta name="keywords" content="#{@meta.meta_keywords}">) if @meta.meta_keywords.present? -%>
  <%= raw %(<link rel="canonical" content="#{@canonical}" />) if @canonical.present? -%>
  <%= csrf_meta_tags if Refinery::Core.authenticity_token_on_frontend -%>
  <%= yield :meta %>

  <%= stylesheet_link_tag "application", "formatting", "theme" %>
  <%= stylesheet_link_tag "home" if home_page? %>
  <%= yield :stylesheets %>

  <%= render '/refinery/google_analytics' %>

  <%= javascript_include_tag 'modernizr-min' %>
</head>

app/views/refinery/_header.html.erb
<h1 id='logo'>
  <%= link_to Refinery::Core.site_name, refinery.root_path %>
</h1>
<%= render(:partial => "/refinery/menu", :locals => {
             :dom_id => 'menu',
             :css => 'menu'
           }) %>

app/views/refinery/_html_tag.html.erb
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html lang="<%= ::I18n.locale %>" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="<%= ::I18n.locale %>" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="<%= ::I18n.locale %>" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="<%= ::I18n.locale %>" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="<%= ::I18n.locale %>" class="no-js"> <!--<![endif]-->

app/views/refinery/_ie6check.html.erb
<% if Refinery::Core.ie6_upgrade_message_enabled -%>
  <% unless admin? %>
  <!--[if lte IE 6]>
    <div id="ie6msg_wrapper">
      <div id="ie6msg">
        <h4>Did you know that your browser is out of date?</h4>
        <div id='ie6message'>
          <p>
            To get the best possible experience using our website we recommend that you upgrade your browser to a newer version. The current version is
            <a class="getie8" href="http://upgradeie.s3.amazonaws.com/eng/index.html">Internet Explorer 8</a>.
            The upgrade is free. If you're using a PC at work you should contact your IT administrator.
          </p>
          <p>
            If you want to you may also try some other popular and <strong>free</strong> Internet browsers like:<br/>
            <a class="ie6expl" href="http://www.google.com/chrome" target='_blank'>Google Chrome</a>,
            <a class="ie6expl" href="http://www.apple.com/safari/download/" target='_blank'>Safari</a>,
            <a class="ie6expl" href="http://getfirefox.com" target='_blank'>Firefox</a> or
            <a class="ie6expl" href="http://www.opera.com" target='_blank'>Opera</a>
          </p>
        </div>
      </div>
    </div>
  <![endif]-->
  <% else %>
    <!--[if lte IE 8]>
      <div id='upgrade_wrapper'>
        <h2>Want to have a better experience with Refinery?</h2>
        <p>
          To get the best possible experience using Refinery, we recommend that you switch your web browser.
        </p>
        <p>
          There are a number of web browsers available that will give you a better experience and they are all available <strong>free of charge</strong>. Installing a new web browser will not remove Internet Explorer which you will still be able to use when you need to.
        </p>
        <p>
          <ul>
            <li>
              <a class="ie6expl" href="http://www.google.com/chrome" target='_blank'>Google Chrome</a>
            </li>
            <li>
              <a class="ie6expl" href="http://www.apple.com/safari/download/" target='_blank'>Apple Safari</a>
            </li>
            <li>
              <a class="ie6expl" href="http://getfirefox.com" target='_blank'>Mozilla Firefox</a>
            </li>
            <li>
              <a class="ie6expl" href="http://www.opera.com" target='_blank'>Opera</a>
            </li>
          </ul>
        </p>
      </div>
    <![endif]-->
    <% content_for :javascripts do %>
      <script>
        $(document).ready(function() {
          $('#flash.flash_message:has("#upgrade_wrapper") #flash_close').click(function(e) {
            e.preventDefault();
            $.get('<%= refinery.admin_disable_upgrade_message_path %>');
          });
        });
      </script>
    <% end %>
  <% end %>
<% end -%>

app/views/refinery/_javascripts.html.erb
<%= yield :before_javascript_libraries -%>
<%= yield :javascript_libraries %>
<%= yield :after_javascript_libraries %>
<% if request.env['HTTP_USER_AGENT'] =~ /MSIE/ %>
  <!--[if lt IE 7 ]>
    <%= javascript_include_tag 'dd_belatedpng' %>
    <script> DD_belatedPNG.fix('img, .png_bg'); //fix any <img> or .png_bg background-images </script>
  <![endif]-->
<% end %>
<%= javascript_include_tag 'application' %>
<%= yield :javascripts -%>

app/views/refinery/_menu.html.erb
<%
  # Collect the root items.
# ::Refinery::Menu is smart enough to remember all of the items in the original collection.
if (roots = local_assigns[:roots] || (collection ||= refinery_menu_pages).roots).present?
  dom_id ||= 'menu'
  css = [(css || 'menu clearfix')].flatten.join(' ')
  hide_children = Refinery::Core.menu_hide_children if hide_children.nil?
-%>
<nav id='<%= dom_id %>' class='<%= css %>'>
<ul>
  <%= render :partial => '/refinery/menu_branch', :collection => roots,
    :locals => {
    :hide_children => hide_children,
    :sibling_count => (roots.length - 1),
    :menu_levels => local_assigns[:menu_levels],
    :apply_css => true #if you don't care about class='first' class='last' or class='selected' set apply_css to false for speed.
  } -%>
  <% if user_signed_in? %>
    <li><%= link_to '首页', home_path %></li>
    <li><%= link_to '退出', destroy_user_session_path, method: :delete %></li>
    <li><%= link_to '修改密码', modify_password_user_registration_path %></li>
  <% else %>
    <li><%= link_to "登录", main_app.new_user_session_path %></li>
    <li><%= link_to "注册", main_app.new_user_registration_path %></li>
  <% end %>
</ul>
</nav>
<% end -%>

app/views/refinery/_menu_branch.html.erb
<%
  if !!local_assigns[:apply_css] and (classes = menu_branch_css(local_assigns)).any?
    css = "class='#{classes.join(' ')}'".html_safe
  end
-%>
<li<%= ['', css].compact.join(' ').gsub(/\ *$/, '').html_safe %>>
<%= link_to(menu_branch.title, refinery.url_for(menu_branch.url)) -%>
  <% if ( (children = menu_branch.children unless hide_children).present? &&
          (!local_assigns[:menu_levels] || menu_branch.ancestors.length < local_assigns[:menu_levels]) ) -%>
    <ul class='clearfix'>
      <%= render :partial => '/refinery/menu_branch', :collection => children,
                 :locals => {
                   :apply_css => local_assigns[:apply_css],
                   :hide_children => !!hide_children,
                   :menu_levels => local_assigns[:menu_levels]
                 } -%>
    </ul>
  <% end -%>
</li>

app/views/refinery/_message.html.erb
<% flash.each do |key, value| %>
<div id='flash' class="flash flash_<%= key %>" style='visibility: hidden;' >
  <%= value %>
  <%= link_to t(".close#{'_this_message' if key.to_s == "message"}"), "",
              :id => "flash_close" %>
</div>
<% end %>

app/views/refinery/_no_script.html.erb
<noscript>
  <div class='flash flash_error'>
    <%= t('.enable_javascript_html') %>
    <%= t('.here_are') %>
    <%= link_to t('.instructions_enable_javascript_html'),
                'http://www.enable-javascript.com',
                :target => '_blank' %>
  </div>
</noscript>

app/views/refinery/_site_bar.html.erb
<% if refinery_user? && "#{controller_name}##{action_name}" != 'pages#preview' %>
  <% unless admin? # all required JS included by backend. %>
    <% content_for :stylesheets, stylesheet_link_tag('refinery/site_bar') unless !!local_assigns[:exclude_css] %>
    <%= yield(:stylesheets) unless local_assigns[:head] or local_assigns[:exclude_css] %>
  <% end -%>
  <div id='site_bar'>
    <div id='site_bar_content' class='clearfix'>
      <div id='editor_switch'>
        <%= site_bar_switch_link -%>
      </div>
      <%= link_to image_tag("#{"http://refinerycms.com/images/" unless local_request?}refinery/logo-site-bar.png", :alt => "Refinery (tm) Content Manager"),
                  'http://refinerycms.com',
                  :target => '_blank',
                  :id => 'site_bar_refinery_cms_logo' %>

      <div id='site_bar_branding'>
        <span id='site_bar_company_name'>
          <%= Refinery::Core.site_name %>
        </span>

        <%= link_to t('.log_out', site_bar_translate_locale_args),
                    refinery.destroy_refinery_user_session_path, :id => 'logout' %>
      </div>
    </div>
  </div>
<% end %>